using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using RRMonitoring.Identity.Domain.Entities;

namespace RRMonitoring.Identity.Infrastructure.Database.EntityConfigurations;

public class CountryConfiguration : IEntityTypeConfiguration<Country>
{
	public void Configure(EntityTypeBuilder<Country> builder)
	{
		builder
			.ToTable("country");

		builder
			.HasKey(x => x.Id);

		builder.Property(x => x.Name)
			.IsRequired()
			.HasMaxLength(100);

		builder
			.Property(x => x.Code)
			.IsRequired()
			.HasMaxLength(2);

		builder
			.HasData(GetDefaultCountries());
	}

	private static IList<Country> GetDefaultCountries()
	{
		return new List<Country>
		{
			new() { Id = 1, Name = "Остров Вознесения", Code = "AC", IsActive = true },
			new() { Id = 2, Name = "Андорра", Code = "AD", IsActive = true },
			new() { Id = 3, Name = "Объединённые Арабские Эмираты", Code = "AE", IsActive = true },
			new() { Id = 4, Name = "Афганистан", Code = "AF", IsActive = true },
			new() { Id = 5, Name = "Антигуа и Барбуда", Code = "AG", IsActive = true },
			new() { Id = 6, Name = "Ангилья", Code = "AI", IsActive = true },
			new() { Id = 7, Name = "Албания", Code = "AL", IsActive = true },
			new() { Id = 8, Name = "Армения", Code = "AM", IsActive = true },
			new() { Id = 9, Name = "Ангола", Code = "AO", IsActive = true },
			new() { Id = 10, Name = "Аргентина", Code = "AR", IsActive = true },
			new() { Id = 11, Name = "Американское Самоа", Code = "AS", IsActive = true },
			new() { Id = 12, Name = "Австрия", Code = "AT", IsActive = true },
			new() { Id = 13, Name = "Австралия", Code = "AU", IsActive = true },
			new() { Id = 14, Name = "Аруба", Code = "AW", IsActive = true },
			new() { Id = 15, Name = "Аландские острова", Code = "AX", IsActive = true },
			new() { Id = 16, Name = "Азербайджан", Code = "AZ", IsActive = true },
			new() { Id = 17, Name = "Босния и Герцеговина", Code = "BA", IsActive = true },
			new() { Id = 18, Name = "Барбадос", Code = "BB", IsActive = true },
			new() { Id = 19, Name = "Бангладеш", Code = "BD", IsActive = true },
			new() { Id = 20, Name = "Бельгия", Code = "BE", IsActive = true },
			new() { Id = 21, Name = "Буркина-Фасо", Code = "BF", IsActive = true },
			new() { Id = 22, Name = "Болгария", Code = "BG", IsActive = true },
			new() { Id = 23, Name = "Бахрейн", Code = "BH", IsActive = true },
			new() { Id = 24, Name = "Бурунди", Code = "BI", IsActive = true },
			new() { Id = 25, Name = "Бенин", Code = "BJ", IsActive = true },
			new() { Id = 26, Name = "Сен-Бартелеми", Code = "BL", IsActive = true },
			new() { Id = 27, Name = "Бермудские острова", Code = "BM", IsActive = true },
			new() { Id = 28, Name = "Бруней", Code = "BN", IsActive = true },
			new() { Id = 29, Name = "Боливия", Code = "BO", IsActive = true },
			new() { Id = 30, Name = "Бонэйр, Синт-Эстатиус и Саба", Code = "BQ", IsActive = true },
			new() { Id = 31, Name = "Бразилия", Code = "BR", IsActive = true },
			new() { Id = 32, Name = "Багамы", Code = "BS", IsActive = true },
			new() { Id = 33, Name = "Бутан", Code = "BT", IsActive = true },
			new() { Id = 34, Name = "Ботсвана", Code = "BW", IsActive = true },
			new() { Id = 35, Name = "Беларусь", Code = "BY", IsActive = true },
			new() { Id = 36, Name = "Белиз", Code = "BZ", IsActive = true },
			new() { Id = 37, Name = "Канада", Code = "CA", IsActive = true },
			new() { Id = 38, Name = "Кокосовые острова", Code = "CC", IsActive = true },
			new() { Id = 39, Name = "Конго - Киншаса", Code = "CD", IsActive = true },
			new() { Id = 40, Name = "Центрально-Африканская Республика", Code = "CF", IsActive = true },
			new() { Id = 41, Name = "Конго - Браззавиль", Code = "CG", IsActive = true },
			new() { Id = 42, Name = "Швейцария", Code = "CH", IsActive = true },
			new() { Id = 43, Name = "Кот-д'Ивуар", Code = "CI", IsActive = true },
			new() { Id = 44, Name = "Острова Кука", Code = "CK", IsActive = true },
			new() { Id = 45, Name = "Чили", Code = "CL", IsActive = true },
			new() { Id = 46, Name = "Камерун", Code = "CM", IsActive = true },
			new() { Id = 47, Name = "Китай", Code = "CN", IsActive = true },
			new() { Id = 48, Name = "Колумбия", Code = "CO", IsActive = true },
			new() { Id = 49, Name = "Коста-Рика", Code = "CR", IsActive = true },
			new() { Id = 50, Name = "Куба", Code = "CU", IsActive = true },
			new() { Id = 51, Name = "Кабо-Верде", Code = "CV", IsActive = true },
			new() { Id = 52, Name = "Кюрасао", Code = "CW", IsActive = true },
			new() { Id = 53, Name = "Остров Рождества", Code = "CX", IsActive = true },
			new() { Id = 54, Name = "Кипр", Code = "CY", IsActive = true },
			new() { Id = 55, Name = "Чехия", Code = "CZ", IsActive = true },
			new() { Id = 56, Name = "Германия", Code = "DE", IsActive = true },
			new() { Id = 57, Name = "Джибути", Code = "DJ", IsActive = true },
			new() { Id = 58, Name = "Дания", Code = "DK", IsActive = true },
			new() { Id = 59, Name = "Доминика", Code = "DM", IsActive = true },
			new() { Id = 60, Name = "Доминиканская Республика", Code = "DO", IsActive = true },
			new() { Id = 61, Name = "Алжир", Code = "DZ", IsActive = true },
			new() { Id = 62, Name = "Эквадор", Code = "EC", IsActive = true },
			new() { Id = 63, Name = "Эстония", Code = "EE", IsActive = true },
			new() { Id = 64, Name = "Египет", Code = "EG", IsActive = true },
			new() { Id = 65, Name = "Западная Сахара", Code = "EH", IsActive = true },
			new() { Id = 66, Name = "Эритрея", Code = "ER", IsActive = true },
			new() { Id = 67, Name = "Испания", Code = "ES", IsActive = true },
			new() { Id = 68, Name = "Эфиопия", Code = "ET", IsActive = true },
			new() { Id = 69, Name = "Финляндия", Code = "FI", IsActive = true },
			new() { Id = 70, Name = "Фиджи", Code = "FJ", IsActive = true },
			new() { Id = 71, Name = "Фолклендские (Мальвинские) острова", Code = "FK", IsActive = true },
			new() { Id = 72, Name = "Федеративные Штаты Микронезии", Code = "FM", IsActive = true },
			new() { Id = 73, Name = "Фарерские острова", Code = "FO", IsActive = true },
			new() { Id = 74, Name = "Франция", Code = "FR", IsActive = true },
			new() { Id = 75, Name = "Габон", Code = "GA", IsActive = true },
			new() { Id = 76, Name = "Великобритания", Code = "GB", IsActive = true },
			new() { Id = 77, Name = "Гренада", Code = "GD", IsActive = true },
			new() { Id = 78, Name = "Грузия", Code = "GE", IsActive = true },
			new() { Id = 79, Name = "Французская Гвиана", Code = "GF", IsActive = true },
			new() { Id = 80, Name = "Гернси", Code = "GG", IsActive = true },
			new() { Id = 81, Name = "Гана", Code = "GH", IsActive = true },
			new() { Id = 82, Name = "Гибралтар", Code = "GI", IsActive = true },
			new() { Id = 83, Name = "Гренландия", Code = "GL", IsActive = true },
			new() { Id = 84, Name = "Гамбия", Code = "GM", IsActive = true },
			new() { Id = 85, Name = "Гвинея", Code = "GN", IsActive = true },
			new() { Id = 86, Name = "Гваделупа", Code = "GP", IsActive = true },
			new() { Id = 87, Name = "Экваториальная Гвинея", Code = "GQ", IsActive = true },
			new() { Id = 88, Name = "Греция", Code = "GR", IsActive = true },
			new() { Id = 89, Name = "Гватемала", Code = "GT", IsActive = true },
			new() { Id = 90, Name = "Гуам", Code = "GU", IsActive = true },
			new() { Id = 91, Name = "Гвинея-Бисау", Code = "GW", IsActive = true },
			new() { Id = 92, Name = "Гайана", Code = "GY", IsActive = true },
			new() { Id = 93, Name = "Гонконг", Code = "HK", IsActive = true },
			new() { Id = 94, Name = "Гондурас", Code = "HN", IsActive = true },
			new() { Id = 95, Name = "Хорватия", Code = "HR", IsActive = true },
			new() { Id = 96, Name = "Гаити", Code = "HT", IsActive = true },
			new() { Id = 97, Name = "Венгрия", Code = "HU", IsActive = true },
			new() { Id = 98, Name = "Индонезия", Code = "ID", IsActive = true },
			new() { Id = 99, Name = "Ирландия", Code = "IE", IsActive = true },
			new() { Id = 100, Name = "Израиль", Code = "IL", IsActive = true },
			new() { Id = 101, Name = "Остров Мэн", Code = "IM", IsActive = true },
			new() { Id = 102, Name = "Индия", Code = "IN", IsActive = true },
			new()
			{
				Id = 103, Name = "Британская территория в Индийском океане", Code = "IO", IsActive = true
			},
			new() { Id = 104, Name = "Ирак", Code = "IQ", IsActive = true },
			new() { Id = 105, Name = "Иран", Code = "IR", IsActive = true },
			new() { Id = 106, Name = "Исландия", Code = "IS", IsActive = true },
			new() { Id = 107, Name = "Италия", Code = "IT", IsActive = true },
			new() { Id = 108, Name = "Джерси", Code = "JE", IsActive = true },
			new() { Id = 109, Name = "Ямайка", Code = "JM", IsActive = true },
			new() { Id = 110, Name = "Иордания", Code = "JO", IsActive = true },
			new() { Id = 111, Name = "Япония", Code = "JP", IsActive = true },
			new() { Id = 112, Name = "Кения", Code = "KE", IsActive = true },
			new() { Id = 113, Name = "Киргизия", Code = "KG", IsActive = true },
			new() { Id = 114, Name = "Камбоджа", Code = "KH", IsActive = true },
			new() { Id = 115, Name = "Кирибати", Code = "KI", IsActive = true },
			new() { Id = 116, Name = "Коморы", Code = "KM", IsActive = true },
			new() { Id = 117, Name = "Сент-Китс и Невис", Code = "KN", IsActive = true },
			new() { Id = 118, Name = "КНДР", Code = "KP", IsActive = true },
			new() { Id = 119, Name = "Республика Корея", Code = "KR", IsActive = true },
			new() { Id = 120, Name = "Кувейт", Code = "KW", IsActive = true },
			new() { Id = 121, Name = "Острова Кайман", Code = "KY", IsActive = true },
			new() { Id = 122, Name = "Казахстан", Code = "KZ", IsActive = true },
			new() { Id = 123, Name = "Лаос", Code = "LA", IsActive = true },
			new() { Id = 124, Name = "Ливан", Code = "LB", IsActive = true },
			new() { Id = 125, Name = "Сент-Люсия", Code = "LC", IsActive = true },
			new() { Id = 126, Name = "Лихтенштейн", Code = "LI", IsActive = true },
			new() { Id = 127, Name = "Шри-Ланка", Code = "LK", IsActive = true },
			new() { Id = 128, Name = "Либерия", Code = "LR", IsActive = true },
			new() { Id = 129, Name = "Лесото", Code = "LS", IsActive = true },
			new() { Id = 130, Name = "Литва", Code = "LT", IsActive = true },
			new() { Id = 131, Name = "Люксембург", Code = "LU", IsActive = true },
			new() { Id = 132, Name = "Латвия", Code = "LV", IsActive = true },
			new() { Id = 133, Name = "Ливия", Code = "LY", IsActive = true },
			new() { Id = 134, Name = "Марокко", Code = "MA", IsActive = true },
			new() { Id = 135, Name = "Монако", Code = "MC", IsActive = true },
			new() { Id = 136, Name = "Молдова", Code = "MD", IsActive = true },
			new() { Id = 137, Name = "Черногория", Code = "ME", IsActive = true },
			new() { Id = 138, Name = "Сен-Мартен", Code = "MF", IsActive = true },
			new() { Id = 139, Name = "Мадагаскар", Code = "MG", IsActive = true },
			new() { Id = 140, Name = "Маршалловы острова", Code = "MH", IsActive = true },
			new() { Id = 141, Name = "Северная Македония", Code = "MK", IsActive = true },
			new() { Id = 142, Name = "Мали", Code = "ML", IsActive = true },
			new() { Id = 143, Name = "Мьянма (Бирма)", Code = "MM", IsActive = true },
			new() { Id = 144, Name = "Монголия", Code = "MN", IsActive = true },
			new() { Id = 145, Name = "Макао", Code = "MO", IsActive = true },
			new() { Id = 146, Name = "Северные Марианские острова", Code = "MP", IsActive = true },
			new() { Id = 147, Name = "Мартиника", Code = "MQ", IsActive = true },
			new() { Id = 148, Name = "Мавритания", Code = "MR", IsActive = true },
			new() { Id = 149, Name = "Монтсеррат", Code = "MS", IsActive = true },
			new() { Id = 150, Name = "Мальта", Code = "MT", IsActive = true },
			new() { Id = 151, Name = "Маврикий", Code = "MU", IsActive = true },
			new() { Id = 152, Name = "Мальдивы", Code = "MV", IsActive = true },
			new() { Id = 153, Name = "Малави", Code = "MW", IsActive = true },
			new() { Id = 154, Name = "Мексика", Code = "MX", IsActive = true },
			new() { Id = 155, Name = "Малайзия", Code = "MY", IsActive = true },
			new() { Id = 156, Name = "Мозамбик", Code = "MZ", IsActive = true },
			new() { Id = 157, Name = "Намибия", Code = "NA", IsActive = true },
			new() { Id = 158, Name = "Новая Каледония", Code = "NC", IsActive = true },
			new() { Id = 159, Name = "Нигер", Code = "NE", IsActive = true },
			new() { Id = 160, Name = "Остров Норфолк", Code = "NF", IsActive = true },
			new() { Id = 161, Name = "Нигерия", Code = "NG", IsActive = true },
			new() { Id = 162, Name = "Никарагуа", Code = "NI", IsActive = true },
			new() { Id = 163, Name = "Нидерланды", Code = "NL", IsActive = true },
			new() { Id = 164, Name = "Норвегия", Code = "NO", IsActive = true },
			new() { Id = 165, Name = "Непал", Code = "NP", IsActive = true },
			new() { Id = 166, Name = "Науру", Code = "NR", IsActive = true },
			new() { Id = 167, Name = "Ниуэ", Code = "NU", IsActive = true },
			new() { Id = 168, Name = "Новая Зеландия", Code = "NZ", IsActive = true },
			new() { Id = 169, Name = "Оман", Code = "OM", IsActive = true },
			new() { Id = 170, Name = "Панама", Code = "PA", IsActive = true },
			new() { Id = 171, Name = "Перу", Code = "PE", IsActive = true },
			new() { Id = 172, Name = "Французская Полинезия", Code = "PF", IsActive = true },
			new() { Id = 173, Name = "Папуа - Новая Гвинея", Code = "PG", IsActive = true },
			new() { Id = 174, Name = "Филиппины", Code = "PH", IsActive = true },
			new() { Id = 175, Name = "Пакистан", Code = "PK", IsActive = true },
			new() { Id = 176, Name = "Польша", Code = "PL", IsActive = true },
			new() { Id = 177, Name = "Сен-Пьер и Микелон", Code = "PM", IsActive = true },
			new() { Id = 178, Name = "Пуэрто-Рико", Code = "PR", IsActive = true },
			new() { Id = 179, Name = "Палестина", Code = "PS", IsActive = true },
			new() { Id = 180, Name = "Португалия", Code = "PT", IsActive = true },
			new() { Id = 181, Name = "Палау", Code = "PW", IsActive = true },
			new() { Id = 182, Name = "Парагвай", Code = "PY", IsActive = true },
			new() { Id = 183, Name = "Катар", Code = "QA", IsActive = true },
			new() { Id = 184, Name = "Реюньон", Code = "RE", IsActive = true },
			new() { Id = 185, Name = "Румыния", Code = "RO", IsActive = true },
			new() { Id = 186, Name = "Сербия", Code = "RS", IsActive = true },
			new() { Id = 187, Name = "Россия", Code = "RU", IsActive = true },
			new() { Id = 188, Name = "Руанда", Code = "RW", IsActive = true },
			new() { Id = 189, Name = "Саудовская Аравия", Code = "SA", IsActive = true },
			new() { Id = 190, Name = "Соломоновы острова", Code = "SB", IsActive = true },
			new() { Id = 191, Name = "Сейшельские острова", Code = "SC", IsActive = true },
			new() { Id = 192, Name = "Судан", Code = "SD", IsActive = true },
			new() { Id = 193, Name = "Швеция", Code = "SE", IsActive = true },
			new() { Id = 194, Name = "Сингапур", Code = "SG", IsActive = true },
			new() { Id = 195, Name = "Остров Святой Елены", Code = "SH", IsActive = true },
			new() { Id = 196, Name = "Словения", Code = "SI", IsActive = true },
			new() { Id = 197, Name = "Шпицберген и Ян-Майен", Code = "SJ", IsActive = true },
			new() { Id = 198, Name = "Словакия", Code = "SK", IsActive = true },
			new() { Id = 199, Name = "Сьерра-Леоне", Code = "SL", IsActive = true },
			new() { Id = 200, Name = "Сан-Марино", Code = "SM", IsActive = true },
			new() { Id = 201, Name = "Сенегал", Code = "SN", IsActive = true },
			new() { Id = 202, Name = "Сомали", Code = "SO", IsActive = true },
			new() { Id = 203, Name = "Суринам", Code = "SR", IsActive = true },
			new() { Id = 204, Name = "Южный Судан", Code = "SS", IsActive = true },
			new() { Id = 205, Name = "Сан-Томе и Принсипи", Code = "ST", IsActive = true },
			new() { Id = 206, Name = "Сальвадор", Code = "SV", IsActive = true },
			new() { Id = 207, Name = "Синт-Мартен", Code = "SX", IsActive = true },
			new() { Id = 208, Name = "Сирия", Code = "SY", IsActive = true },
			new() { Id = 209, Name = "Эсватини", Code = "SZ", IsActive = true },
			new() { Id = 210, Name = "Тёркс и Кайкос", Code = "TC", IsActive = true },
			new() { Id = 211, Name = "Чад", Code = "TD", IsActive = true },
			new() { Id = 212, Name = "Того", Code = "TG", IsActive = true },
			new() { Id = 213, Name = "Таиланд", Code = "TH", IsActive = true },
			new() { Id = 214, Name = "Таджикистан", Code = "TJ", IsActive = true },
			new() { Id = 215, Name = "Токелау", Code = "TK", IsActive = true },
			new() { Id = 216, Name = "Восточный Тимор", Code = "TL", IsActive = true },
			new() { Id = 217, Name = "Туркменистан", Code = "TM", IsActive = true },
			new() { Id = 218, Name = "Тунис", Code = "TN", IsActive = true },
			new() { Id = 219, Name = "Тонга", Code = "TO", IsActive = true },
			new() { Id = 220, Name = "Турция", Code = "TR", IsActive = true },
			new() { Id = 221, Name = "Тринидад и Тобаго", Code = "TT", IsActive = true },
			new() { Id = 222, Name = "Тувалу", Code = "TV", IsActive = true },
			new() { Id = 223, Name = "Тайвань", Code = "TW", IsActive = true },
			new() { Id = 224, Name = "Танзания", Code = "TZ", IsActive = true },
			new() { Id = 225, Name = "Украина", Code = "UA", IsActive = true },
			new() { Id = 226, Name = "Уганда", Code = "UG", IsActive = true },
			new() { Id = 227, Name = "Соединенные Штаты", Code = "US", IsActive = true },
			new() { Id = 228, Name = "Уругвай", Code = "UY", IsActive = true },
			new() { Id = 229, Name = "Узбекистан", Code = "UZ", IsActive = true },
			new() { Id = 230, Name = "Ватикан", Code = "VA", IsActive = true },
			new() { Id = 231, Name = "Сент-Винсент и Гренадины", Code = "VC", IsActive = true },
			new() { Id = 232, Name = "Венесуэла", Code = "VE", IsActive = true },
			new() { Id = 233, Name = "Виргинские острова (Великобритания)", Code = "VG", IsActive = true },
			new() { Id = 234, Name = "Виргинские острова (США)", Code = "VI", IsActive = true },
			new() { Id = 235, Name = "Вьетнам", Code = "VN", IsActive = true },
			new() { Id = 236, Name = "Вануату", Code = "VU", IsActive = true },
			new() { Id = 237, Name = "Уоллис и Футуна", Code = "WF", IsActive = true },
			new() { Id = 238, Name = "Самоа", Code = "WS", IsActive = true },
			new() { Id = 239, Name = "Косово", Code = "XK", IsActive = true },
			new() { Id = 240, Name = "Йемен", Code = "YE", IsActive = true },
			new() { Id = 241, Name = "Майотта", Code = "YT", IsActive = true },
			new() { Id = 242, Name = "Южно-Африканская Республика", Code = "ZA", IsActive = true },
			new() { Id = 243, Name = "Замбия", Code = "ZM", IsActive = true },
			new() { Id = 244, Name = "Зимбабве", Code = "ZW", IsActive = true }
		};
	}
}
